PACKAGE := ncurses
VERSION := 5.9-20110507
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://ftp.gnu.org/gnu/$(PACKAGE)/$(ARCHIVE)"
MD5     := "49dc7136424f2bdd653439eda63a2375"

include ../common.mk
