PACKAGE := pari
VERSION := 2.9.1
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://pari.math.u-bordeaux.fr/pub/$(PACKAGE)/unix/$(ARCHIVE)"
SHA256  := "dc510f96686463c1ade7c2a6e16fa9466fd4af6a65fddf9822ba07d7d2e70767"

FILES_TO_FIX := bin/gp-2.9-real lib/libpari-gmp.dylib

include ../common.mk
