PACKAGE := pari
VERSION := 2.9.4
DIRNAME := $(PACKAGE)-$(VERSION)
ARCHIVE := $(DIRNAME).tar.gz
URL     := http://pari.math.u-bordeaux.fr/pub/$(PACKAGE)/unix/$(ARCHIVE)
SHA256  := 4f9cdc739630a039c0fcc9afac2e5647659c4a709dcc6f7a69d5908cd4a82647

FILES_TO_FIX := bin/gp-2.9-real lib/libpari-gmp.dylib

include ../common.mk
