PACKAGE := automake
VERSION := 1.14
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://ftp.gnu.org/gnu/$(PACKAGE)/$(ARCHIVE)"
MD5     := "a3c0d9298c6112f5f2c26c639ccaaed7"

include ../common.mk
