PACKAGE := automake
VERSION := 1.15
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://ftp.gnu.org/gnu/$(PACKAGE)/$(ARCHIVE)"
MD5     := "716946a105ca228ab545fc37a70df3a3"

include ../common.mk
