PACKAGE := singular
VERSION := 4.0.1
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www.mathematik.uni-kl.de/ftp/pub/Math/Singular/SOURCES/4-0-1/$(ARCHIVE)"
MD5     := "13c385fb1ea6bc105115f496cea55bf2"

include ../common.mk
