PACKAGE := mpc
VERSION := 1.0.3
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www.multiprecision.org/$(PACKAGE)/download/$(ARCHIVE)"
MD5     := "d6a1d5f8ddea3abd2cc3e98f58352d26"

CONFIGURE_PARAMS := --disable-static
FILES_TO_FIX := lib/libmpc.3.dylib

include ../common.mk
