PACKAGE := mpc
VERSION := 1.0.2
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www.multiprecision.org/$(PACKAGE)/download/$(ARCHIVE)"
MD5     := "68fadff3358fb3e7976c7a398a0af4c3"

include ../common.mk
