PACKAGE := ntl
VERSION := 6.2.1
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www.shoup.net/ntl/$(ARCHIVE)"
MD5     := "00b7e1cab9bf9b0eae2ad9beab4b0fc9"

include ../common.mk
