PACKAGE := ntl
VERSION := 11.0.0
DIRNAME := $(PACKAGE)-$(VERSION)
ARCHIVE := $(DIRNAME).tar.gz
URL     := http://www.shoup.net/ntl/$(ARCHIVE)
SHA256  := e34c3a57e3b913dcf59ecc4d2c1927c614f99db55d2cebe3edd65973eb91ddec
WWW     := http://www.shoup.net/ntl/

FILES_TO_FIX := lib/libntl.dylib

include ../common.mk
