PACKAGE := ntl
VERSION := 10.3.0
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www.shoup.net/ntl/$(ARCHIVE)"
SHA256  := "717b8d519d66f383a6ae938e255ee4dd103dbab77e4e828dc9cbb0749ec4c1f4"

FILES_TO_FIX := lib/libntl.*.dylib

include ../common.mk
