PACKAGE := mpfi
VERSION := 1.5.1
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "https://gforge.inria.fr/frs/download.php/30129/$(ARCHIVE)"
MD5     := "ce788b73b62eca1945db2ef453ee1364"

include ../common.mk
