PACKAGE := libtool
VERSION := 2.4.6
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://ftp.gnu.org/gnu/$(PACKAGE)/$(ARCHIVE)"
MD5     := "addf44b646ddb4e3919805aa88fa7c5e"

include ../common.mk
