PACKAGE := 4ti2
VERSION := 1.6.7
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www.4ti2.de/version_$(VERSION)/$(ARCHIVE)"
MD5     := "90def0d6b01a0247e439356777467497"

FILES_TO_FIX := \
    bin/4ti2gmp \
    bin/4ti2int32 \
    bin/4ti2int64 \
    bin/genmodel \
    bin/gensymm \
    bin/output \
    bin/ppi \
    bin/zsolve

include ../common.mk
