PACKAGE := 4ti2
VERSION := 1.6.2
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www.4ti2.de/version_$(VERSION)/$(ARCHIVE)"
MD5     := "b4c10243725aa964c041453058e15942"

FILES_TO_FIX := \
    bin/4ti2gmp \
    bin/4ti2int32 \
    bin/4ti2int64 \
    bin/genmodel \
    bin/gensymm \
    bin/output \
    bin/ppi \
    bin/zsolve

include ../common.mk
