#!/bin/sh -e

# Determine the location of this script
dir="$(cd "$(dirname "$0")" && pwd)"

# Launch the actual start script in a terminal
TERMINAL_APP="Terminal"
#TERMINAL_APP="iTerm"
open -a $TERMINAL_APP "$dir/gap.start"

exit 0

# TODO: allow user to choose between Terminal.app and iTerm
