PACKAGE := flint
VERSION := 2.4.4
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www.flintlib.org/$(ARCHIVE)"
MD5     := "b527fe3a49fd02a0367227fe8ec9cbe4"

#BuildDepends: gmp5 (>= 5.1.3-3), libmpfr4 (>= 3.0.0)

include ../common.mk
