GAP_PACKAGES += float

gap/pkg/float: cxsc fplll mpc mpfi mpfr
#DEPENDENCIES := cxsc fplll mpc mpfi mpfr

# HACK: float-0.5.18 is missing some autogenerated files, so we
# need to add them via autotools
gap/pkg/float: autoconf automake libtool
