PACKAGE := cxsc
VERSION := 2-5-4
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www2.math.uni-wuppertal.de/~xsc/xsc/$(PACKAGE)/$(ARCHIVE)"
SHA256  := "fd0d824fd94bef3aae55b95e5ef19342b653fe3ff4fb561364e942c809eb616b"

include ../common.mk
