PACKAGE := cxsc
VERSION := 2-5-4
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www2.math.uni-wuppertal.de/~xsc/xsc/$(PACKAGE)/$(ARCHIVE)"
MD5     := "5f1dafed3daf365332aa8b5dca298119"

include ../common.mk
