PACKAGE := boost
VERSION := 1_63_0
ARCHIVE := "$(PACKAGE)_$(VERSION).tar.bz2"
DIRNAME := "$(PACKAGE)_$(VERSION)"
URL     := "http://downloads.sourceforge.net/$(PACKAGE)/$(ARCHIVE)"
SHA256  := "beae2529f759f6b3bf3f4969a19c2e9d6f0c503edcb2de4a61d1428519fcb3b0"

FILES_TO_FIX := lib/libboost_atomic.dylib

include ../common.mk
