PACKAGE := boost
VERSION := 1_60_0
ARCHIVE := "$(PACKAGE)_$(VERSION).tar.bz2"
DIRNAME := "$(PACKAGE)_$(VERSION)"
URL     := "http://downloads.sourceforge.net/$(PACKAGE)/$(ARCHIVE)"
SHA256  := "686affff989ac2488f79a97b9479efb9f2abae035b5ed4d8226de6857933fd3b"

FILES_TO_FIX := lib/libboost_atomic.dylib

include ../common.mk
