PACKAGE := boost
VERSION := 1_56_0
ARCHIVE := "$(PACKAGE)_$(VERSION).tar.bz2"
DIRNAME := "$(PACKAGE)_$(VERSION)"
URL     := "http://downloads.sourceforge.net/$(PACKAGE)/$(ARCHIVE)"
MD5     := "a744cf167b05d72335f27c88115f211d"

FILES_TO_FIX := lib/libboost_atomic.dylib

include ../common.mk
