PACKAGE := normaliz
VERSION := 2.12
ARCHIVE := "Normaliz$(VERSION).zip"
DIRNAME := "Normaliz2.12"
URL     := "http://www.home.uni-osnabrueck.de/wbruns/normaliz/Normaliz$(VERSION)/$(ARCHIVE)"
MD5     := "c3ce3937bcc9c27462b63abc6db41a4e"

include ../common.mk
