PACKAGE := normaliz
VERSION := 3.0.0
ARCHIVE := Normaliz$(VERSION)Source.zip
DIRNAME := Normaliz3.0
URL     := "http://www.home.uni-osnabrueck.de/wbruns/normaliz/$(DIRNAME)/$(ARCHIVE)"
MD5     := "a8eba69dff3e4844d5a1a11b5f402b17"

include ../common.mk
