PACKAGE := gmp
VERSION := 6.0.0a
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.bz2"
#DIRNAME := "$(PACKAGE)-$(VERSION)"
DIRNAME := "$(PACKAGE)-6.0.0"
URL     := "http://ftp.gnu.org/gnu/$(PACKAGE)/$(ARCHIVE)"
MD5     := "b7ff2d88cae7f8085bd5006096eed470"

include ../common.mk
