PACKAGE := cmake
VERSION := 3.4.3
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www.cmake.org/files/v3.4/$(ARCHIVE)"
MD5     := "4cb3ff35b2472aae70f542116d616e63"

include ../common.mk
