PACKAGE := cmake
VERSION := 3.4.3
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www.cmake.org/files/v3.4/$(ARCHIVE)"
SHA256  := "b73f8c1029611df7ed81796bf5ca8ba0ef41c6761132340c73ffe42704f980fa"

include ../common.mk
