PACKAGE := cmake
VERSION := 3.0.2
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://www.cmake.org/files/v3.0/$(ARCHIVE)"
MD5     := "db4c687a31444a929d2fdc36c4dfb95f"

include ../common.mk
