PACKAGE := glpk
VERSION := 4.61
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://ftp.gnu.org/gnu/$(PACKAGE)/$(ARCHIVE)"
SHA256  := "9866de41777782d4ce21da11b88573b66bb7858574f89c28be6967ac22dfaba9"
# https://www.gnu.org/software/glpk/

FILES_TO_FIX := bin/glpsol lib/libglpk.*.dylib

include ../common.mk
