PACKAGE := glpk
VERSION := 4.58
ARCHIVE := "$(PACKAGE)-$(VERSION).tar.gz"
DIRNAME := "$(PACKAGE)-$(VERSION)"
URL     := "http://ftp.gnu.org/gnu/$(PACKAGE)/$(ARCHIVE)"
SHA256  := "4460fa417a747b1913b4a3b3000c1e6a6296aa8980688c73cf963f4880f2b9ca"
# https://www.gnu.org/software/glpk/

FILES_TO_FIX := bin/glpsol lib/libglpk.*.dylib

include ../common.mk
